### ISSUE TITLE
script for figure1 a

### ISSUE THREAD

**Issue by taojinsheng** [xhhuanglab/QTN_scripts#1]
Dear Professor Huang,

I looked through all the scripts here and didn't find the script for heatmap in figure 1a.It would be greatly appreciated if you could tell me how to generate this figure.

Best,

Jinsheng

**Comment by lefroyqiu** [comment]
Hi Jinsheng,

Thanks for asking. It was drawn simply by 'pheatmap' R package (script: Causal_Var_heatmap_plot.r). Then we combined it with a  separate phylogenetic tree figure made by Mega. Of course, samples are ordered based on the tree before plotting the heatmap.

Best,
Jie Qiu

**Comment by taojinsheng** [comment]
Hi Jie,

Thanks for your prompt reply. I checked the script and noticed that legend were set to FALSE.So did you generate the legend at the bottom by hand?Also,were the row annotations on the left generated by hand?

Best,
Jinsheng

**Comment by lefroyqiu** [comment]
Hi Jinsheng,
Yes, further detailed annotations and legends were added by hand.
Best,
Jie
